workflows:
  ios-unsigned-build:
    name: iOS Unsigned Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.ilan2004.nudge # Replace with your actual bundle ID
      vars:
        XCODE_WORKSPACE: "Nudge.xcworkspace" # Update if using .xcworkspace
        XCODE_PROJECT: "Nudge.xcodeproj"     # Update with actual project name
        XCODE_SCHEME: "Nudge"                # Update with your scheme name
        BUNDLE_ID: "com.ilan2004.nudge"      # Replace with your bundle ID
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          # For unsigned builds, we'll create a temporary keychain and certificate
          # This step can be skipped if you want completely unsigned builds
          echo "Setting up for unsigned build"
      - name: Set up code signing settings on Xcode project
        script: |
          # Disable automatic code signing
          if [ -f "$XCODE_PROJECT/project.pbxproj" ]; then
            xcode-project use-profiles
          fi
      - name: Get CocoaPods dependencies
        script: |
          if [ -f "Podfile" ]; then
            pod install
          fi
      - name: Build ipa for distribution
        script: |
          # Build unsigned IPA
          if [ -f "$XCODE_WORKSPACE" ]; then
            xcode-project build-ipa \
              --workspace "$XCODE_WORKSPACE" \
              --scheme "$XCODE_SCHEME" \
              --config "Release" \
              --destination "generic/platform=iOS" \
              --export-options-plist /tmp/export_options.plist
          else
            xcode-project build-ipa \
              --project "$XCODE_PROJECT" \
              --scheme "$XCODE_SCHEME" \
              --config "Release" \
              --destination "generic/platform=iOS" \
              --export-options-plist /tmp/export_options.plist
          fi
      - name: Create export options for unsigned build
        script: |
          cat > /tmp/export_options.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <false/>
              <key>compileBitcode</key>
              <false/>
          </dict>
          </plist>
          EOF
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      # Uncomment and configure if you want to publish to external services
      # slack:
      #   channel: '#ios-builds'
      #   notify_on_build_start: true
      #   notify:
      #     success: true
      #     failure: true
      email:
        recipients:
          - your-email@example.com # Replace with your email
        notify:
          success: true
          failure: true
