workflows:
  ios-unsigned-build:
    name: iOS Unsigned Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "Nudge.xcworkspace" # Update if using .xcworkspace
        XCODE_PROJECT: "Nudge.xcodeproj"     # Update with actual project name
        XCODE_SCHEME: "Nudge"                # Update with your scheme name
        BUNDLE_ID: "com.ilan2004.nudge"      # Replace with your bundle ID
      xcode: latest
      cocoapods: default
    scripts:
      - name: Disable code signing for unsigned build
        script: |
          echo "Preparing for unsigned build - disabling code signing"
      - name: Get CocoaPods dependencies
        script: |
          if [ -f "Podfile" ]; then
            pod install
          fi
      - name: Build unsigned IPA
        script: |
          # Create export options for unsigned build first
          cat > /tmp/export_options.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>signingCertificate</key>
              <string>-</string>
              <key>provisioningProfiles</key>
              <dict/>
              <key>stripSwiftSymbols</key>
              <false/>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <false/>
              <key>compileBitcode</key>
              <false/>
          </dict>
          </plist>
          EOF
          
          # Build unsigned IPA
          if [ -f "$XCODE_WORKSPACE" ]; then
            xcodebuild archive \
              -workspace "$XCODE_WORKSPACE" \
              -scheme "$XCODE_SCHEME" \
              -configuration Release \
              -destination "generic/platform=iOS" \
              -archivePath "$PWD/build/Nudge.xcarchive" \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO \
              CODE_SIGNING_ALLOWED=NO \
              PROVISIONING_PROFILE=""
          else
            xcodebuild archive \
              -project "$XCODE_PROJECT" \
              -scheme "$XCODE_SCHEME" \
              -configuration Release \
              -destination "generic/platform=iOS" \
              -archivePath "$PWD/build/Nudge.xcarchive" \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO \
              CODE_SIGNING_ALLOWED=NO \
              PROVISIONING_PROFILE=""
          fi
          
          # Export unsigned IPA
          xcodebuild -exportArchive \
            -archivePath "$PWD/build/Nudge.xcarchive" \
            -exportPath "$PWD/build/ios/ipa" \
            -exportOptionsPlist /tmp/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - build/Nudge.xcarchive
      - /tmp/xcodebuild_logs/*.log
    publishing:
      # Uncomment and configure if you want to publish to external services
      # slack:
      #   channel: '#ios-builds'
      #   notify_on_build_start: true
      #   notify:
      #     success: true
      #     failure: true
      email:
        recipients:
          - your-email@example.com # Replace with your email
        notify:
          success: true
          failure: true
